version: '3'

services:
  cpu:
    build: .
    volumes:
      - ./:/app
    environment:
      - CUDA_VISIBLE_DEVICES=
    command: bash -c "cd /app/doomrnn && bash extract.bash"
    
  gpu:
    build: .
    volumes:
      - ./:/app
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: bash -c "cd /app/doomrnn && bash gpu_jobs.bash"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
  train:
    build: .
    volumes:
      - ./:/app
    environment:
      - CUDA_VISIBLE_DEVICES=
    command: bash -c "cd /app/doomrnn && python train.py"
